image: node:14

variables:
  CI_USER: $CI_USER
  CI_USER_PASSWORD: $CI_USER_PASSWORD

before_script:
  - echo "//registry.npmjs.org/:_authToken=${NPM_REGISTRY_TOKEN}" > .npmrc
  - npm ci --cache .npm --prefer-offline

cache:
  key: "logger" # universal cache
  paths:
    - .npm/

test:
  stage: test
  script:
    - npm run pretest
    - npm run coverage
  artifacts:
    reports:
      junit: report.xml
    expire_in: 1 week


deploy:
  stage: deploy
  script:
    - npm run build
    - if (npx semver $CI_COMMIT_TAG --range '>0.0.0'); then NPM_TAG=latest; else NPM_TAG=beta; fi; # Using the fact that semver by default considers that pre-releases do not respect stable ranges
    - npm publish --tag=$NPM_TAG
  only:
    - tags
