/* eslint-env mocha */
import { assert } from 'chai'
import makeLogger, { setHistorySize, flushToString } from './index.js'
import * as path from 'path'
import { execFile } from 'child_process'
import { promisify } from 'util'

const exec = (env, file) => promisify(execFile)(process.execPath, [path.join(__dirname, './spawnedTests', file)], { env })

const log = makeLogger('log-level-test')

describe('spawned tests', () => {
  describe('test environment Variables Alias', () => {
    describe('test LOG_LEVEL environment', () => {
      it('test LOG_LEVEL scoped namespace debug Level', async () => {
        const { stdout, stderr } = await exec({ LOG_LEVEL: 'log-level-test:debug' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 5)
        assert.include(lines[0], 'this should be debug level')
        assert.include(lines[1], 'this should be info level')
        assert.include(lines[2], 'this should be warn level')
        assert.include(lines[3], 'this should be debug level')
        assert.strictEqual(lines[4], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test LOG_LEVEL wildcard namespace debug Level', async () => {
        const { stdout, stderr } = await exec({ LOG_LEVEL: '*:debug' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 5)
        assert.include(lines[0], 'this should be debug level')
        assert.include(lines[1], 'this should be info level')
        assert.include(lines[2], 'this should be warn level')
        assert.include(lines[3], 'this should be debug level')
        assert.strictEqual(lines[4], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test LOG_LEVEL scoped namespace info Level', async () => {
        const { stdout, stderr } = await exec({ LOG_LEVEL: 'log-level-test:info' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 4)
        assert.include(lines[0], 'this should be info level')
        assert.include(lines[1], 'this should be warn level')
        assert.include(lines[2], 'this should be debug level')
        assert.strictEqual(lines[3], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test LOG_LEVEL wildcard namespace info Level', async () => {
        const { stdout, stderr } = await exec({ LOG_LEVEL: '*:info' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 4)
        assert.include(lines[0], 'this should be info level')
        assert.include(lines[1], 'this should be warn level')
        assert.include(lines[2], 'this should be debug level')
        assert.strictEqual(lines[3], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test LOG_LEVEL scoped namespace warn Level', async () => {
        const { stdout, stderr } = await exec({ LOG_LEVEL: 'log-level-test:warn' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 3)
        assert.include(lines[0], 'this should be warn level')
        assert.include(lines[1], 'this should be debug level')
        assert.strictEqual(lines[2], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test LOG_LEVEL wildcard namespace warn Level', async () => {
        const { stdout, stderr } = await exec({ LOG_LEVEL: '*:warn' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 3)
        assert.include(lines[0], 'this should be warn level')
        assert.include(lines[1], 'this should be debug level')
        assert.strictEqual(lines[2], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test LOG_LEVEL scoped namespace error Level', async () => {
        const { stdout, stderr } = await exec({ LOG_LEVEL: 'log-level-test:error' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 2)
        assert.include(lines[0], 'this should be debug level')
        assert.strictEqual(lines[1], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test LOG_LEVEL wildcard namespace error Level', async () => {
        const { stdout, stderr } = await exec({ LOG_LEVEL: '*:error' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 2)
        assert.include(lines[0], 'this should be debug level')
        assert.strictEqual(lines[1], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
    })

    describe('test DEBUG environment', () => {
      it('test DEBUG scoped namespace debug Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG: 'log-level-test:debug' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 5)
        assert.include(lines[0], 'this should be debug level')
        assert.include(lines[1], 'this should be info level')
        assert.include(lines[2], 'this should be warn level')
        assert.include(lines[3], 'this should be debug level')
        assert.strictEqual(lines[4], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG wildcard namespace debug Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG: '*:debug' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 5)
        assert.include(lines[0], 'this should be debug level')
        assert.include(lines[1], 'this should be info level')
        assert.include(lines[2], 'this should be warn level')
        assert.include(lines[3], 'this should be debug level')
        assert.strictEqual(lines[4], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG scoped namespace info Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG: 'log-level-test:info' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 4)
        assert.include(lines[0], 'this should be info level')
        assert.include(lines[1], 'this should be warn level')
        assert.include(lines[2], 'this should be debug level')
        assert.strictEqual(lines[3], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG wildcard namespace info Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG: '*:info' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 4)
        assert.include(lines[0], 'this should be info level')
        assert.include(lines[1], 'this should be warn level')
        assert.include(lines[2], 'this should be debug level')
        assert.strictEqual(lines[3], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG scoped namespace warn Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG: 'log-level-test:warn' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 3)
        assert.include(lines[0], 'this should be warn level')
        assert.include(lines[1], 'this should be debug level')
        assert.strictEqual(lines[2], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG wildcard namespace warn Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG: '*:warn' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 3)
        assert.include(lines[0], 'this should be warn level')
        assert.include(lines[1], 'this should be debug level')
        assert.strictEqual(lines[2], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG scoped namespace error Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG: 'log-level-test:error' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 2)
        assert.include(lines[0], 'this should be debug level')
        assert.strictEqual(lines[1], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })

      it('test DEBUG wildcard namespace error Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG: '*:error' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 2)
        assert.include(lines[0], 'this should be debug level')
        assert.strictEqual(lines[1], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
    })

    describe('test DEBUG_NAMESPACES environment', () => {
      it('test DEBUG_NAMESPACES scoped namespace debug Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG_NAMESPACES: 'log-level-test:debug' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 5)
        assert.include(lines[0], 'this should be debug level')
        assert.include(lines[1], 'this should be info level')
        assert.include(lines[2], 'this should be warn level')
        assert.include(lines[3], 'this should be debug level')
        assert.strictEqual(lines[4], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG_NAMESPACES wildcard namespace debug Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG_NAMESPACES: '*:debug' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 5)
        assert.include(lines[0], 'this should be debug level')
        assert.include(lines[1], 'this should be info level')
        assert.include(lines[2], 'this should be warn level')
        assert.include(lines[3], 'this should be debug level')
        assert.strictEqual(lines[4], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG_NAMESPACES scoped namespace info Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG_NAMESPACES: 'log-level-test:info' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 4)
        assert.include(lines[0], 'this should be info level')
        assert.include(lines[1], 'this should be warn level')
        assert.include(lines[2], 'this should be debug level')
        assert.strictEqual(lines[3], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG_NAMESPACES wildcard namespace info Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG_NAMESPACES: '*:info' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 4)
        assert.include(lines[0], 'this should be info level')
        assert.include(lines[1], 'this should be warn level')
        assert.include(lines[2], 'this should be debug level')
        assert.strictEqual(lines[3], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG_NAMESPACES scoped namespace warn Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG_NAMESPACES: 'log-level-test:warn' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 3)
        assert.include(lines[0], 'this should be warn level')
        assert.include(lines[1], 'this should be debug level')
        assert.strictEqual(lines[2], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG_NAMESPACES wildcard namespace warn Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG_NAMESPACES: '*:warn' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 3)
        assert.include(lines[0], 'this should be warn level')
        assert.include(lines[1], 'this should be debug level')
        assert.strictEqual(lines[2], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG_NAMESPACES scoped namespace error Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG_NAMESPACES: 'log-level-test:error' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 2)
        assert.include(lines[0], 'this should be debug level')
        assert.strictEqual(lines[1], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
      it('test DEBUG_NAMESPACES wildcard namespace error Level', async () => {
        const { stdout, stderr } = await exec({ DEBUG_NAMESPACES: '*:error' }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 2)
        assert.include(lines[0], 'this should be debug level')
        assert.strictEqual(lines[1], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
    })

    describe('test environment when undefined', () => {
      it('test undefined', async () => {
        const { stdout, stderr } = await exec({ }, 'logLevel.js')
        const lines = stdout.split('\n')
        assert.strictEqual(lines.length, 4)
        assert.include(lines[0], 'this should be info level')
        assert.include(lines[1], 'this should be warn level')
        assert.include(lines[2], 'this should be debug level')
        assert.strictEqual(lines[3], '')

        const linesErr = stderr.split('\n')
        assert.strictEqual(linesErr.length, 2)
        assert.include(linesErr[0], 'this should be error level')
        assert.strictEqual(linesErr[1], '')
      })
    })
  })
  describe('test logger when crashed and given to type objects', () => {
    it('test logger when crashed with controlled object type', async () => {
      const { stdout } = await exec({ }, 'logControlledObject.js')
      assert.include(stdout, 'Couldn\'t output log because tu ne me stringifieras pas')
    })
    it('test logger with error type ', async () => {
      const { stderr } = await exec({ }, 'logErrorType.js')
      assert.include(stderr, 'error:log-error-type')
      assert.include(stderr, 'Error message')
      assert.include(stderr, 'code: MY_CODE')
    })
    it('test logger with undefined', async () => {
      const { stdout } = await exec({ }, 'logUndefined.js')
      assert.include(stdout, 'undefined')
    })
    it('test type objects', async () => {
      const { stdout } = await exec({ }, 'logAllTypes.js')
      assert.include(stdout, 'test')
      assert.include(stdout, '1')
      assert.include(stdout, '{\n  "foo": "bar"\n}')
      assert.include(stdout, 'null')
      assert.include(stdout, 'true')
      assert.include(stdout, 'Symbol(symbol)')
      assert.include(stdout, '() => {\n  console.log(\'test\');\n}\n')
    })
    it('test type objects with multiple arguments', async () => {
      const { stdout } = await exec({ }, 'logMultipleArgs.js')
      assert.include(stdout, 'test test test')
    })
  })
})

describe('test setHistorySize and flushToString', () => {
  it('test setHistorySize with fewer logs than history size', async () => {
    setHistorySize(5)
    log.debug('this should be debug level 1')
    log.debug('this should be debug level 2')
    log.debug('this should be debug level 3')
    const result = flushToString()
    const lines = result.split('\n')
    assert.strictEqual(lines.length, 3)
    assert.include(lines[0], 'this should be debug level 1')
    assert.include(lines[1], 'this should be debug level 2')
    assert.include(lines[2], 'this should be debug level 3')
  })
  it('test setHistorySize with more logs than history size', async () => {
    setHistorySize(5)
    log.debug('this should be debug level 4')
    log.debug('this should be debug level 5')
    log.debug('this should be debug level 6')

    const result2 = flushToString()
    const lines2 = result2.split('\n')
    assert.strictEqual(lines2.length, 5)
    assert.include(lines2[0], 'this should be debug level 2')
    assert.include(lines2[1], 'this should be debug level 3')
    assert.include(lines2[2], 'this should be debug level 4')
    assert.include(lines2[3], 'this should be debug level 5')
    assert.include(lines2[4], 'this should be debug level 6')
  })
})
